### ISSUE TITLE
problems with ekphrasis

### ISSUE THREAD

**Issue by amirim** [cbaziotis/ntua-slp-semeval2018#2]
Hi,

I'm trying to run your code on GPU by running the following command:
`python ./model/pretraining/sentiment2017.py`

 but the following errors occur. Can you help me with that ?

` Running on:cuda
Traceback (most recent call last):
  File "./model/pretraining/sentiment2017.py", line 17, in <module>
    from utils.train import define_trainer, model_training
  File "/root/ntua-slp-semeval2018/utils/train.py", line 21, in <module>
    from modules.nn.dataloading import WordDataset, CharDataset
  File "/root/ntua-slp-semeval2018/modules/nn/dataloading.py", line 7, in <module>
    from ekphrasis.classes.preprocessor import TextPreProcessor
  File "/usr/local/lib/python2.7/dist-packages/ekphrasis/classes/preprocessor.py", line 6, in <module>
    from ekphrasis.classes.exmanager import ExManager
  File "/usr/local/lib/python2.7/dist-packages/ekphrasis/classes/exmanager.py", line 19
    {print(k.lower(), ":", self.expressions[k])
         ^
SyntaxError: invalid syntax
`

**Comment by amirim** [comment]
Thanks, it works with python3.
Now there is another problem when running the script: sentiment2017.py:   word2vec_300_6_concatened.txt is missing.

**Comment by cbaziotis** [comment]
This is a word embeddings file. Follow the instruction in the ReadMe (Prerequisites): 

1. Download an embeddings file https://github.com/cbaziotis/ntua-slp-semeval2018#2---download-our-pre-trained-word-embeddings
2. Update the model congig https://github.com/cbaziotis/ntua-slp-semeval2018#3---update-model-configs

**Comment by amirim** [comment]
but the file names are: ntua_twitter_300.txt/ ntua_twitter_affect_310.txt, and I'm searching these files: word2vec_300_6_20_neg.txt", 
word2vec_300_6_concatened.txt
word2vec_500_6_20_neg.txt", 
word2vec_500_6_concatened.txt

**Comment by cbaziotis** [comment]
Go here https://github.com/cbaziotis/ntua-slp-semeval2018/blob/master/model/params.py#L216
Change it to the embeddings file that you want...
