### ISSUE TITLE
code takes longer to pre process trian data

### ISSUE THREAD

**Issue by coolabhishek** [cbaziotis/ntua-slp-semeval2018#6]
No cache file for TASK3_A_word_train ...
PreProcessing dataset TASK3_A_word_train...:   2%|▏         | 63/3834 [00:00<00:40, 93.01it/s]

It keeps waiting at 2%.

Even when I try to load using GPU or only CPU. gold set was very fast and took 3 minutes to process

**Comment by cbaziotis** [comment]
This issue is related to ekphrasis, which is a dependency of this project. See also https://github.com/cbaziotis/datastories-semeval2017-task4/issues/38. 

I just increased the cache sizes in ekphrasis. Please upgrade:
```
pip install ekphrasis -U
```
