### ISSUE TITLE
Testing working setup does not work

### ISSUE THREAD

**Issue by amosbastian** [cbaziotis/ntua-slp-semeval2018#9]
After following all prerequisites, starting the visdom server and trying to run `python model/pretraining/sentiment2017.py` I get the following error

```
Traceback (most recent call last):
  File "model/pretraining/sentiment2017.py", line 9, in <module>
    from config import DATA_DIR
ModuleNotFoundError: No module named 'config'
```
which makes complete sense, as there is no `config.py` file in that folder. I've tried moving the `config.py` file found in the root directory to that folder, and after running it again, it gives the following error

```
Running on:cpu
Traceback (most recent call last):
  File "model/pretraining/sentiment2017.py", line 10, in <module>
    from dataloaders.rest import load_data_from_dir
ModuleNotFoundError: No module named 'dataloaders'
```

I've then also moved `sentiment2017.py` to the root folder, and then run it from there with `python sentiment2017.py`, which sort of works. It starts up, takes about 5 minutes to get to ~4%, and then just hangs there as far as I can tell.

```
PreProcessing dataset SEMEVAL_2017_word_train...:   4%| | 2240/58761 [05:10<2:10:32,  7.22it/s]
```

Any idea what is happening? I am using Python 3.6 (and also had to install some packages that aren't included in the requirements.txt), but when using Python 2.7 I get a different error. Also not sure why the instructions in the README don't work for me and I have to copy and move files around either.

**Comment by davidhelbig** [comment]
Hi, I was able to circumvent the import problems by running the file as a module from the root folder. `python -m model.pretraining.sentiment2017` did the trick for me.

**Comment by agn-7** [comment]
@amosbastian You should use the following style to deal with import error:

`python -m model.pretraining.sentiment2017.py`

or 

`python -m model.pretraining.sentiment2017.py`

[A relevant StackOverflow post](https://stackoverflow.com/questions/22241420/execution-of-python-code-with-m-option-or-not)
